# Global cross-platform CLI packages. Apply with: brew bundle --file Brewfile
brew "ast-grep"
brew "bat"
brew "btop"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "jq"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "unzip"
brew "uv"
brew "wget"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh"

tap "oven-sh/bun"
brew "oven-sh/bun/bun"
